# Script for reading .csv files generated by DualSPHysics
# Plots Velocity Profiles at a point

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from matplotlib.ticker import FormatStrFormatter

################################################################
#roughness value 0
df_0 = pd.read_csv("_PointsVelocity_Vel.x0.csv", delimiter=';',skiprows=[0,1,2,3])
df_025 = pd.read_csv("_PointsVelocity_Vel.x025.csv", delimiter=';',skiprows=[0,1,2,3])
df_05 = pd.read_csv("_PointsVelocity_Vel.x05.csv", delimiter=';',skiprows=[0,1,2,3])
df_1 = pd.read_csv("_PointsVelocity_Vel.x1.csv", delimiter=';',skiprows=[0,1,2,3])
df_5 = pd.read_csv("_PointsVelocity_Vel.x5.csv", delimiter=';',skiprows=[0,1,2,3])


'''
################################################################
# roughness value 0.25
df_025 = pd.read_csv("_PointsVelocity_Vel.x025.csv", delimiter=';',skiprows=[0])

df_025.drop(["Part"],axis = 1,inplace = True) # removes Part and Time columns
df_025.drop(["Time"],axis = 1,inplace = True)

i = 0
for i in range(0,800): # removes all y and z velocity components
    stringName_y = "Vel_%s.y" % i
    stringName_z = "Vel_%s.z" % i

    df_025.drop([stringName_y],axis = 1,inplace = True)
    df_025.drop([stringName_z],axis = 1,inplace = True)


################################################################
# roughness value 0.5
df_05 = pd.read_csv("_PointsVelocity_Vel.x05.csv", delimiter=';',skiprows=[0])

df_05.drop(["Part"],axis = 1,inplace = True) # removes Part and Time columns
df_05.drop(["Time"],axis = 1,inplace = True)

i = 0
for i in range(0,800): # removes all y and z velocity components
    stringName_y = "Vel_%s.y" % i
    stringName_z = "Vel_%s.z" % i

    df_05.drop([stringName_y],axis = 1,inplace = True)
    df_05.drop([stringName_z],axis = 1,inplace = True)


################################################################
# roughness value 1
df_1 = pd.read_csv("_PointsVelocity_Vel.x1.csv", delimiter=';',skiprows=[0])

df_1.drop(["Part"],axis = 1,inplace = True) # removes Part and Time columns
df_1.drop(["Time"],axis = 1,inplace = True)

i = 0
for i in range(0,800): # removes all y and z velocity components
    stringName_y = "Vel_%s.y" % i
    stringName_z = "Vel_%s.z" % i

    df_1.drop([stringName_y],axis = 1,inplace = True)
    df_1.drop([stringName_z],axis = 1,inplace = True)


###############################################################
# roughness value 5
df_5 = pd.read_csv("_PointsVelocity_Vel.x5.csv", delimiter=';',skiprows=[0])

df_5.drop(["Part"],axis = 1,inplace = True) # removes Part and Time columns
df_5.drop(["Time"],axis = 1,inplace = True)

i = 0
for i in range(0,800): # removes all y and z velocity components
    stringName_y = "Vel_%s.y" % i
    stringName_z = "Vel_%s.z" % i

    df_5.drop([stringName_y],axis = 1,inplace = True)
    df_5.drop([stringName_z],axis = 1,inplace = True)

'''
depthvals = np.linspace(0,0.08,800)

print(df_5.iloc[140])


velprofile_0 = df_0.iloc[149] # select 200th row
velprofile_025 = df_025.iloc[149] # select 200th rowfiggyfi
velprofile_05 = df_05.iloc[149] # select 200th row
velprofile_1 = df_1.iloc[149] # select 200th row
velprofile_5 = df_5.iloc[149] # select 200th row


fig, ax = plt.subplots()
labelfont = {'fontname':'Times New Roman'}
#plt.title('Velocity profiles at different ',**labelfont)

plt.plot(velprofile_0[1:801],depthvals,label="$\\alpha_{FB} / \\alpha_{FF} = 0$")
plt.plot(velprofile_025[1:801],depthvals,label="$\\alpha_{FB} / \\alpha_{FF} = 0.25$")
plt.plot(velprofile_05[1:801],depthvals,label="$\\alpha_{FB} / \\alpha_{FF} = 0.5$")
plt.plot(velprofile_1[1:801],depthvals,label="$\\alpha_{FB} / \\alpha_{FF} = 1$")
plt.plot(velprofile_5[1:801],depthvals,label="$\\alpha_{FB} / \\alpha_{FF} = 5$")
plt.ylabel('y (m)',**labelfont)
plt.xlabel('x-velocity (m/s)',**labelfont)
plt.grid(True)

plt.legend()
#plt.ylim((0.001,0.475))
#plt.xlim((0.0,10.2))

plt.show()



