# Script for reading .csv files generated by DualSPHysics

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from matplotlib.ticker import FormatStrFormatter

df = pd.read_csv("PointsVelocity_Vel.csv", delimiter=';',skiprows=[0])

df.drop(["Part"],axis = 1,inplace = True) # removes Part and Time columns
df.drop(["Time"],axis = 1,inplace = True)

print(df)


i = 0
for i in range(1,1000): # removes all y and z velocity components
    stringName_y = "Vel_%s.y" % i
    stringName_z = "Vel_%s.z" % i

    df.drop([stringName_y],axis = 1,inplace = True)
    df.drop([stringName_z],axis = 1,inplace = True)

# row.shape[0] # gives number of columns in df

row = df.iloc[200] # select 200th row
xvals = np.linspace(0.2,10.16,1002)

print(xvals.shape)
print(row.shape)

fig, ax = plt.subplots()
labelfont = {'fontname':'Times New Roman'}
plt.title('Surface flow velocity (m/s) at centerline of flume along length of flume (m) after 200×0.01s timesteps',**labelfont)
plt.plot(xvals[3:999],row[3:999])
plt.ylabel('Surface Flow Velocity along Centerline of Flume (m/s)',**labelfont)
plt.xlabel('Distance along Flume (m)',**labelfont)
plt.grid(True)

plt.ylim((0.001,0.475))
plt.xlim((0.0,10.2))

ax.axvline(0.2, linestyle='--', color='k') # vertical lines
ax.axvline(5.7, linestyle='--', color='k')
ax.axvline(5.855, linestyle='--', color='k')

ax.xaxis.set_major_formatter(FormatStrFormatter('%s')) # sets string formatter for xaxis labels
ax.set_xticks([0.0, 0.2, 1.0, 2.0, 3.0, 4.0, 5.0, 5.7, 5.855, 6.0, 7.0, 8.0, 9.0,10.0,10.2], minor=False)

plt.xticks(fontsize=7, rotation=65,**labelfont)
plt.yticks(fontsize=7,**labelfont)
plt.show()



